appname: "Play"
layout: "main"
charset: "UTF-8"
template: "simple"

session: "MongoDB"
mongodb_session_db: "play"
mongodb_session_coll: "sessions"

serializer: JSON

plugins:
  "Auth::Twitter":
    consumer_key:     "fkOCnMftQeZBItRnaTipA"
    consumer_secret:  "Yr4UiHIzky8mCn0nMpApea5xc8ClGfvFN7C6XtnH54Y"
    callback_url:     "http://localhost:3000/auth/twitter/callback"
    callback_success: "/auth/twitter"
    callback_fail:    "/fail"
