appname: "Play"
layout: "main"
charset: "UTF-8"
template: "simple"

session: "MongoDB"
mongodb_session_db: "play"
mongodb_session_coll: "sessions"

serializer: JSON

plugins:
  "Auth::Twitter":
    consumer_key:     "IRUAzmA5AjwBTrPQWrCzIQ"
    consumer_secret:  "Cj4hB54BLMYeoG9eEX4fd5gexg02nQLIRJ2S3f0nAH4"
    callback_url:     "http://localhost:3000/auth/twitter/callback"
    callback_success: "/auth/twitter"
    callback_fail:    "/fail"
